version: '3.8'

services:
  web:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password  
      - POSTGRES_DB=mydatabase  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["python", "app.py"]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase

volumes:
  db_data:
  postgres_data: